version: "1.0"
info:
  model: int-scaffold
packages:
- name: Fiv_play3Project
  gitServerName: psdevFIV3
  gitUrl: https://github.com/fivsag/Fiv_play3Project
  gitUsername: fivsag
  gitBranch: main
services:
- serviceName: project.fiv_play3.integrations:JustDADAFlow
  packages:
  - name: Fiv_play3Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.fiv_play3.integrations:ProcessOrderDaDaUS
  packages:
  - name: Fiv_play3Project
    version: "1.0"
